### ISSUE TITLE
When to use underscores?

### ISSUE THREAD

**Issue by gilch** [hylang/hy-style-guide#3]
see also https://github.com/hylang/hy/issues/972

All we've got so far is.
> Look like a lisp, DTRT with it (e.g. dashes turn to underscores, earmuffs turn to all-caps.)

Should we also use dashes for Python's many "dunder" special names like `--init--` or do we keep them as underscores like `__init__`? The latter is more recognizable Python, but the rule would be more consistent if it was "always use dashes". Whatever we choose, it should be stated clearly in the guide. We could also do things like `-_init_-` or `_-init-_` or `--init__` or `__init--`. Yeah, that looks weird, but you're forgetting that `__init__` also looks weird, and then you got used to it. If any of these were standard Hy style, you'd get used to it. We could have a rule like "never mix dashes and underscores", but I don't think that's a good idea. More on that later.

The Python convention for a "private" variable is `_x`. At the module level it gets excluded from the `from <module> import *` by default.  In this case I think keeping the underscore is a better choice, since `-x` is too easily confused with `(- x)`. We do use a dash to mean negation in number literals like `-1`. So maybe "always use dashes" isn't such a good rule. What if we have a "private" compound name like `_foo_bar`? Should that be rendered in Hy as `_foo-bar`? But now we're mixing dashes and underscores. I don't think it looks that bad though.

And finally, inside a class, a double-prefixed attr like `__x` gets mangled to `_classname__x` to avoid conflicts with subclasses. Should we render this as `--x` in Hy? Or `-_x` or `_-x`?

We're not consistent even in the source of Hy's standard library.

**Comment by berkerpeksag** [comment]
This guide is now part of the main repository: https://github.com/hylang/hy/blob/master/docs/style-guide.rst I think we can move those issues to hylang/hy and delete this repo.

**Comment by gilch** [comment]
I've copied over this issue. The other two were no longer applicable. You (who?) can delete this repo now.
